language: node_js

node_js:
- 6
- stable

script:
- npm run lint
- npm run build
- npm run test -- --verbose --coverage

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true

notifications:
  email: false
