language: node_js

node_js:
- stable

script:
- npm run lint
- npm run typecheck
- npm run build
- npm run test -- --verbose --coverage

cache:
  yarn: true
  directories:
  - node_modules

notifications:
  email: false
